<?xml version="1.0"?>
<definitions name="Servicio" targetNamespace="urn:Aritmetica"
     xmlns:tns="urn:Aritmetica"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns="http://schemas.xmlsoap.org/wsdl/">
 
  <message name="Entrada">
    <part name="operando1" type="xsd:float" />
    <part name="operando2" type="xsd:float" />
  </message>
 
  <message name="Salida">
    <part name="respuesta" type="xsd:float" />
  </message>
 
  <portType name="Operaciones">
    <operation name="sumar">
      <input message="tns:Entrada" />
      <output message="tns:Salida" />
    </operation>
    <operation name="restar">
      <input message="tns:Entrada" />
      <output message="tns:Salida" />
    </operation>
  </portType>
 
  <binding name="Enlace" type="tns:Operaciones">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="sumar">
        <soap:operation soapAction="urn:Aritmetica#sumar" />
        <input>
          <soap:body use="encoded" namespace="urn:Aritmetica" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
        </input>
        <output>
          <soap:body use="encoded" namespace="urn:Aritmetica" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
        </output>
    </operation>
    <operation name="restar">
        <soap:operation soapAction="urn:Aritmetica#restar" />
        <input>
          <soap:body use="encoded" namespace="urn:Aritmetica" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />      
        </input>
        <output>
          <soap:body use="encoded" namespace="urn:Aritmetica" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />      
        </output>
    </operation>
  </binding>
 
  <service name="Servicio">
    <port name="Operaciones" binding="tns:Enlace">
      <soap:address location="http://uasb-api.rootcode.com.bo/mcruz/api-soap/soap_servidor.php" />
    </port>
  </service>

</definitions>
